version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_golang
    restart: always
    volumes:
      - mysql_golang:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devbook
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
    ports:
        - 3306:3306

volumes:
    mysql_golang: {}